'use strict';

var isPlainObject = require('lodash.isplainobject');
var values = require('lodash.values');
var assign = require('lodash.assign');

// _toConsumableArray is generated by babel: https://babeljs.org/
function _toConsumableArray(arr) {
  if (Array.isArray(arr)) {
    for (var i = 0, arr2 = Array(arr.length); i < arr.length; i++) {
      arr2[i] = arr[i];
    }
    return arr2;
  } else {
    return Array.from(arr);
  }
}

function HtmlWebpackTemplateLiteralPlugin() {
}

HtmlWebpackTemplateLiteralPlugin.prototype.apply = function (compiler) {
  compiler.plugin('compilation', function (compilation) {
    compilation.plugin('html-webpack-plugin-before-html-processing', function (htmlPluginData, callback) {
      var data = htmlPluginData.plugin.options.indexHtmlData;
      if (!isPlainObject(data)) {
        console.warn('indexHtmlData option in HtmlWebpackTemplateLiteralPlugin must be an object');
        return callback();
      }
      data = assign({
        publicPath: compilation.outputOptions.publicPath || '',
        assets: Object.keys(compilation.assets).filter(function (name) {
          return !/\.map$/i.test(name);
        }),
        webpack: compilation.getStats(),
        webpackConfig: compilation.options,
        pluginAssets: assign({
          json: htmlPluginData.plugin.assetJson
        }, htmlPluginData.assets)
      }, data);
      // htmlPluginData.html = new Function(...Object.keys(data), `return \`${htmlPluginData.html}\``)(...values(data));
      htmlPluginData.html = new (Function.prototype.bind.apply(Function, [null].concat(_toConsumableArray(Object.keys(data)), ["return `" + htmlPluginData.html + "`"])))().apply(undefined, _toConsumableArray(values(data)));

      callback(null, htmlPluginData);
    });
  });
}

module.exports = HtmlWebpackTemplateLiteralPlugin;
